name: Test

on:
  pull_request:
    types:
      - 'opened'

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Module
        run: npm i
      - name: Lint
        run: npm run lint
  integration_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
          mongodb-db: test
      - name: Install Module
        run: npm i
      - name: 'Integration'
        run: npm run test:e2e
